// The interactive tour script (v6 — the developer's full rewrite,
// 2026-09-09): explain-then-act pairs everywhere, the whole lifestyle
// selection walkthrough, clear all and empty trash, the recurring rename
// and its new deletion, the week view sequence, and the import sheets.
// Guided and GATED — during a dimmed action step everything except the
// target is dimmed (visual only, so the user can still scroll), and the
// step advances the moment the real action happens.
//
// `host` = which overlay instance shows the step: native modal screens
// (quick-add, day page, the import sheets) paint above the root overlay,
// so those routes render their own overlay instance.
// Copy rules: simple words, short sentences, no semicolons, no em dashes.
import type { TourEvent } from './events';

export type TourHost = 'tabs' | 'quick-add' | 'day' | 'import' | 'import-help';

export type TourStep = {
  id: string;
  kind: 'action' | 'spotlight';
  host: TourHost;
  anchor?: string;
  tab?: '/' | '/daily' | '/calendar' | '/settings';
  title: string;
  body: string;
  webBody?: string;
  placement: 'top' | 'bottom';
  /** Pin the card to one edge regardless of the ring (e.g. the date
   *  picker expands BELOW the chips — the card must stay out of its way). */
  cardPin?: 'top' | 'bottom';
  /** Action steps: dim + block everything except the anchor hole. */
  dim?: boolean;
  /** Spotlights only: skip the darkening entirely — the page stays fully
   *  visible (and interactive) behind the card (developer 2026-09-09:
   *  "no need for the grey out, keep the content there"). */
  noDim?: boolean;
  advanceOn?: TourEvent;
  /** Failsafe: any of these ALSO advances (wrong-but-close actions). */
  advanceOnAny?: TourEvent[];
  advanceOnPath?: string;
  advanceOnPathPrefix?: string;
};

export const TOUR_STEPS: TourStep[] = [
  // ------------------------- Build a task -------------------------
  {
    id: 'add',
    kind: 'action',
    host: 'tabs',
    anchor: 'fab',
    tab: '/',
    title: 'Make your first task',
    body: 'Tap the + button.',
    placement: 'top',
    dim: true,
    advanceOnPath: '/quick-add',
  },
  {
    id: 'name',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-title',
    title: 'Name',
    body: 'Give your task a name. Any name is okay. When you are happy with it, press the checkmark on the keyboard.',
    webBody: 'Give your task a name. Any name is okay. When you are happy with it, press enter.',
    placement: 'bottom',
    advanceOn: 'form-title-committed',
    advanceOnAny: ['form-title-committed', 'form-date-set'],
  },
  {
    id: 'when',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-when',
    title: 'Time and date',
    cardPin: 'top',
    body: 'Tap the date or the time to set your due date. Tapping the same chip again closes it.',
    placement: 'top',
    advanceOn: 'form-date-set',
  },
  {
    id: 'clear-x',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    anchor: 'form-clear-date',
    title: 'No due date',
    body: 'You can also tap the X if the task has no set due date.',
    placement: 'top',
    cardPin: 'top',
  },
  {
    id: 'details',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-details',
    title: 'Details',
    body: 'Tap the Details button.',
    placement: 'top',
    advanceOn: 'form-details-open',
  },
  {
    id: 'priority-info',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    anchor: 'form-priority',
    title: 'Priority',
    body: 'The priority badge ranks tasks. 1st is the most important, 3rd the least. A prioritised task always comes before a normal one.',
    placement: 'top',
  },
  {
    id: 'priority-do',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-priority-first',
    title: 'Pick one',
    body: 'Select the 1st priority.',
    placement: 'top',
    advanceOn: 'form-priority-set',
  },
  // ------------------------- Lifestyles -------------------------
  {
    id: 'lifestyle-info',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    anchor: 'form-lifestyle',
    title: 'Lifestyle',
    body: 'A lifestyle is the part of your life a task belongs to. Home, work, and school are all lifestyles. Picking one sorts the task under it and shows its badge on the card.',
    placement: 'top',
  },
  {
    id: 'lifestyle-new',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-lifestyle-new',
    title: 'Create one',
    body: 'Tap + New. Give it a title, pick a colour, and press Add.',
    placement: 'top',
    advanceOn: 'form-category-set',
  },
  {
    id: 'subjects-info',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    anchor: 'form-subjects',
    title: 'Subjects',
    body: 'Subjects are the smaller parts of a lifestyle. Math class can be a subject in school. A meeting can be a subject in work.',
    placement: 'top',
  },
  {
    id: 'subject-new',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-subject-new',
    title: 'Create a subject',
    body: 'Tap +new and give it a name and a colour.',
    placement: 'top',
    advanceOn: 'form-subject-set',
  },
  {
    id: 'select-notes',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    title: 'Good to know',
    body: 'Tap a selected subject to unselect it. To drop a lifestyle, pick another one, or open the chosen lifestyle and tap it again.',
    placement: 'top',
  },
  {
    id: 'subject-clear',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-subjects',
    title: 'Unselect it',
    body: 'Let us unselect the subject for this task. Tap the subject again.',
    placement: 'top',
    advanceOn: 'form-subject-cleared',
  },
  {
    id: 'lifestyle-confirm',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-lifestyle',
    title: 'Confirm the lifestyle',
    body: 'Tap the lifestyle again to take it on its own.',
    placement: 'top',
    advanceOn: 'form-category-set',
  },
  {
    id: 'select-count',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    title: 'One tap or two',
    body: 'Picking a subject takes one tap. Taking a lifestyle on its own takes one extra tap on the lifestyle.',
    placement: 'top',
  },
  // ------------------------- Notes + create -------------------------
  {
    id: 'notes-info',
    kind: 'spotlight',
    host: 'quick-add',
    noDim: true,
    anchor: 'form-notes',
    title: 'Notes',
    body: 'Anything extra you want to remember goes here. Totally optional.',
    placement: 'top',
  },
  {
    id: 'notes-do',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-notes-input',
    title: 'Add a note',
    body: 'Add a note. Anything goes. A location, extra information, whatever helps. Press the checkmark when done.',
    webBody: 'Add a note. Anything goes. A location, extra information, whatever helps. Press enter when done.',
    placement: 'top',
    advanceOn: 'form-notes-committed',
  },
  {
    id: 'create',
    kind: 'action',
    host: 'quick-add',
    anchor: 'form-submit',
    title: 'Add it',
    body: 'Press Add task.',
    placement: 'top',
    dim: true,
    advanceOn: 'task-created',
  },
  {
    id: 'notes-shown',
    kind: 'spotlight',
    host: 'tabs',
    anchor: 'first-task',
    tab: '/',
    title: 'Notes on the card',
    body: 'The notes always show on the right, empty side of the task.',
    placement: 'bottom',
  },
  // ------------------------- Task actions -------------------------
  {
    id: 'delete',
    kind: 'action',
    host: 'tabs',
    anchor: 'first-task',
    tab: '/',
    title: 'Delete it',
    body: 'There is your task. Swipe it LEFT to delete it. Nothing is ever lost right away.',
    webBody: 'There is your task. Move the mouse to its LEFT edge and click to delete it. Nothing is ever lost right away.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'task-deleted',
    advanceOnAny: ['task-deleted', 'task-completed'],
  },
  {
    id: 'undo',
    kind: 'action',
    host: 'tabs',
    anchor: 'first-task',
    title: 'Bring it back',
    body: 'Tap Undo in the little toast at the bottom. Missed it? Open the Deleted group up top and swipe the task right.',
    webBody: 'Click Undo in the toast at the bottom. Missed it? Open the Deleted group and use the task’s right edge.',
    placement: 'top',
    cardPin: 'bottom',
    advanceOn: 'task-restored',
    advanceOnAny: ['task-restored', 'task-uncompleted'],
  },
  {
    id: 'complete',
    kind: 'action',
    host: 'tabs',
    anchor: 'first-task',
    tab: '/',
    title: 'Complete it',
    body: 'Swipe the task RIGHT to complete it. The same swipe in the Completed group brings it back.',
    webBody: 'Click the task’s RIGHT edge to complete it. The same edge in the Completed group brings it back.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'task-completed',
    advanceOnAny: ['task-completed', 'task-deleted'],
  },
  {
    id: 'bulk-info',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/',
    noDim: true,
    title: 'Clear all and Empty trash',
    body: 'Clear all, next to Completed, moves every completed task into the Deleted group. Empty trash, next to Deleted, permanently deletes everything in it.',
    placement: 'bottom',
    cardPin: 'bottom',
  },
  {
    id: 'clear-all',
    kind: 'action',
    host: 'tabs',
    anchor: 'clear-all',
    tab: '/',
    title: 'Clear the completed',
    body: 'Tap Clear all to send your task to the Deleted group.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'tasks-cleared',
  },
  {
    id: 'empty-trash',
    kind: 'action',
    host: 'tabs',
    anchor: 'empty-trash',
    tab: '/',
    title: 'Empty the trash',
    body: 'Tap Empty trash to permanently remove it.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'trash-emptied',
  },
  // ------------------------- Daily -------------------------
  {
    id: 'to-daily',
    kind: 'spotlight',
    host: 'tabs',
    noDim: true,
    title: 'Next up',
    body: 'Let us move on to the Daily page.',
    placement: 'bottom',
  },
  {
    id: 'daily-intro',
    kind: 'spotlight',
    host: 'tabs',
    anchor: 'daily-header',
    tab: '/daily',
    noDim: true,
    title: 'Daily',
    body: 'The Daily page holds your everyday chores, tasks, and events. Recurring tasks sit at the top, then the tasks due today, then your schedule for the day.',
    placement: 'bottom',
  },
  {
    id: 'recurring-info',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/daily',
    noDim: true,
    title: 'Recurring Tasks',
    body: 'Recurring tasks are things you may do every day. Working out, sketching, practising a hobby, all fit here.',
    placement: 'bottom',
  },
  {
    id: 'recurring-add',
    kind: 'action',
    host: 'tabs',
    anchor: 'daily-add',
    tab: '/daily',
    title: 'Add one',
    body: 'Tap the + row, give it a name, and press enter to create it.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'recurring-added',
  },
  {
    id: 'recurring-how',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/daily',
    noDim: true,
    title: 'Checking off',
    body: 'Tap a recurring task or swipe it right to mark it done. The same action brings it back. Every morning they reset on their own.',
    placement: 'bottom',
  },
  {
    id: 'recurring-delete',
    kind: 'action',
    host: 'tabs',
    anchor: 'first-daily',
    tab: '/daily',
    title: 'Delete one',
    body: 'Hold the task, then confirm to delete it.',
    webBody: 'Right click the task and choose delete.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'recurring-removed',
  },
  {
    id: 'daily-streams',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/daily',
    noDim: true,
    title: 'The rest of the day',
    body: 'Below the recurring tasks sit your tasks and schedule for today. The tasks are condensed so the schedule has room underneath.',
    placement: 'bottom',
  },
  // ------------------------- Calendar -------------------------
  {
    id: 'to-calendar',
    kind: 'spotlight',
    host: 'tabs',
    noDim: true,
    title: 'Next up',
    body: 'Let us move on to the Calendar page.',
    placement: 'bottom',
  },
  {
    id: 'calendar-intro',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/calendar',
    noDim: true,
    title: 'Calendar',
    body: 'The Calendar page shows your tasks and events in a more visual way than the Daily or Tasks pages.',
    placement: 'bottom',
  },
  {
    id: 'cal-years',
    kind: 'action',
    host: 'tabs',
    anchor: 'calendar-year-button',
    tab: '/calendar',
    title: 'Zoom out',
    body: 'Now tap the year on the top left to zoom out from the month view.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'calendar-year-open',
  },
  {
    id: 'cal-scroll',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/calendar',
    noDim: true,
    title: 'Move between years',
    body: 'Like a typical calendar app, scroll up or down to see earlier or later years. An easy way to move far.',
    placement: 'top',
  },
  {
    id: 'cal-zoom-in',
    kind: 'action',
    host: 'tabs',
    anchor: 'year-current-month',
    tab: '/calendar',
    title: 'Zoom back in',
    body: 'Now let us head toward the day view. Tap the current month to zoom back in.',
    placement: 'top',
    dim: true,
    advanceOn: 'calendar-month-open',
  },
  {
    id: 'day-open',
    kind: 'action',
    host: 'tabs',
    tab: '/calendar',
    title: 'Open a day',
    body: 'Tap any day on the grid to see its timeline.',
    placement: 'top',
    advanceOnPathPrefix: '/day',
  },
  {
    id: 'day-tour',
    kind: 'spotlight',
    host: 'day',
    noDim: true,
    title: 'The day timeline',
    body: 'The day timeline draws hour lines for the whole day, like a calendar app. Tasks and events place themselves at their times, and all day events always sit at the top.',
    placement: 'bottom',
  },
  {
    id: 'day-back',
    kind: 'action',
    host: 'day',
    title: 'Head back',
    body: 'Swipe down from the top of the page, or tap Calendar in the corner.',
    webBody: 'Click the empty space beside the page, or tap Calendar in the corner.',
    placement: 'bottom',
    advanceOnPath: '/calendar',
  },
  // ------------------------- Week view -------------------------
  {
    id: 'week-info',
    kind: 'spotlight',
    host: 'tabs',
    anchor: 'week-button',
    tab: '/calendar',
    title: 'Week View',
    body: 'The week view button at the top switches the calendar to a week by week format. There are two week views, a block view and a list view.',
    placement: 'bottom',
  },
  {
    id: 'week-open',
    kind: 'action',
    host: 'tabs',
    anchor: 'week-button',
    tab: '/calendar',
    title: 'Try it',
    body: 'Let us tap the week view button.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'calendar-week-open',
  },
  {
    id: 'week-blocks',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/calendar',
    noDim: true,
    title: 'Week blocks',
    body: 'One tap lands on the week blocks, the first view. The arrows change the week, and the date range between them jumps to any week you pick.',
    placement: 'bottom',
  },
  {
    id: 'week-again',
    kind: 'action',
    host: 'tabs',
    anchor: 'week-button',
    tab: '/calendar',
    title: 'Once more',
    body: 'Let us tap the week view button once more.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'calendar-week-list',
  },
  {
    id: 'week-list',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/calendar',
    noDim: true,
    title: 'Week list',
    body: 'This is the week list. Every event and task in a top to bottom list. Scroll down for the next day.',
    placement: 'bottom',
  },
  {
    id: 'week-close',
    kind: 'action',
    host: 'tabs',
    anchor: 'month-button',
    tab: '/calendar',
    title: 'Back to the month',
    body: 'Let us tap the calendar icon at the top to head back to the month view.',
    placement: 'bottom',
    dim: true,
    advanceOn: 'calendar-week-closed',
  },
  // ------------------------- Events + imports -------------------------
  {
    id: 'events-info',
    kind: 'spotlight',
    host: 'tabs',
    anchor: 'event-buttons',
    tab: '/calendar',
    title: 'Creating and importing events',
    body: 'Events are created two ways. The plus button adds one by hand, full control but slow in bulk. The tray button imports many at once from a CSV file.',
    placement: 'bottom',
  },
  {
    id: 'import-open',
    kind: 'action',
    host: 'tabs',
    anchor: 'import-button',
    tab: '/calendar',
    title: 'Open imports',
    body: 'Tap the import icon near the top right.',
    placement: 'bottom',
    dim: true,
    advanceOnPath: '/import-events',
  },
  {
    id: 'import-sheet',
    kind: 'spotlight',
    host: 'import',
    noDim: true,
    title: 'Importing a CSV',
    body: 'Pick any CSV file on your device, and a colour to match the events being uploaded.',
    placement: 'top',
  },
  {
    id: 'import-help-link',
    kind: 'action',
    host: 'import',
    anchor: 'import-help-link',
    title: 'Need a file?',
    body: 'Not sure how to make a CSV? Tap How do I make a CSV.',
    placement: 'top',
    advanceOnPath: '/import-help',
  },
  {
    id: 'import-ai',
    kind: 'spotlight',
    host: 'import-help',
    noDim: true,
    title: 'The AI prompt',
    body: 'Paste this premade prompt into an AI along with your scheduling data. It writes a CSV tailored to our events. Import that file on the previous page and everything lands on the calendar.',
    placement: 'top',
  },
  {
    id: 'to-settings',
    kind: 'spotlight',
    host: 'import-help',
    noDim: true,
    title: 'Almost done',
    body: 'Now let us move on to the Settings page.',
    placement: 'bottom',
  },
  // ------------------------- Settings -------------------------
  {
    id: 'settings-intro',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/settings',
    noDim: true,
    title: 'Settings',
    body: 'Settings is where you customise and personalise your account, and edit any important personal information.',
    placement: 'bottom',
  },
  {
    id: 'settings-explore',
    kind: 'spotlight',
    host: 'tabs',
    tab: '/settings',
    noDim: true,
    title: 'Yours to explore',
    body: 'It is pretty self explanatory, so explore it on your own time. If you have concerns, improvements, or feedback, fill out the form right here in Settings.',
    placement: 'bottom',
  },
];
